
<script type="text/javascript">
$(document).ready(function(){
	$( ".childcate" ).click(function() {
	  	var id = $(this).attr('id');
	  	var res = id.split("@@");

	  	if (res.length == 3 && $('input[name="condition['+res[1]+']"]').length <= 0){
		  	$('#frmSearch').append("<input type=\"hidden\" name=\"condition["+res[1]+"]\" value=\"" + id + "\">");
		  	$('#frmSearch').append("<input type=\"hidden\" name=\"conditionkey["+res[1]+"]\" value=\"" + res[1] + "\">");
		  	$('#frmSearch').append('<input type="hidden" name="operateElementType" value="1">');
			$('#frmSearch').append('<input type="hidden" name="operateElementName" value="カテゴリー">');
			$('#frmSearch').submit();
	  	}
	});
	$( '.conditiondelete' ).click(function() {
	  	var key = $(this).attr('id');
	  	$('input[name="condition['+key+']"]').remove();
	  	$('input[name="conditionkey['+key+']"]').remove();
	  	
		$('#frmSearch').submit();
	});

	$( ".linkSearchProduct" ).click(function() {
		  	$('#frmSearch').append('<input type="hidden" name="operateElementType" value="0">');
			$('#frmSearch').append('<input type="hidden" name="operateElementName" value="' + $(this).html() + '"/>');
			$('#frmSearch').submit();
	});
});
</script>
<?php $user = $this->userLogin;?>
<form action="<?php echo $this->formaction; ?>" method="get" id="frmSearch">
	<div class="sidebar-offcanvas" id="sidebar" role="navigation">
			<div class="container">
		      	<input type="text" id="keyword" name="keyword" size="16" placeholder="商品を探す" value="<?php echo $this->keyword;?>">
				<!-- <input type="submit" id="submitSearch" value="検索"> -->
				<a href="javascript:void(0);" class="button2 linkSearchProduct">検索</a>
			</div><br>
			<?php if (isset($this->mcontroller) && strcmp($this->mcontroller, 'order')==0):?>
			<h5><b>
		      <span class="glyphicon "></span>&nbsp;注文日</b>
		    </h5>
			<div style="padding: 0 10px 0 10px; text-align: right;"  id="datepairExample" >
                    <input type="text" class="date start" id="start_date" name="start_date" value="<?php echo $this->start_date;?>"/> ～
                    <input type="text" class="date end"  id="end_date" name="end_date" value="<?php echo $this->end_date;?>"/>
                    <input type="submit" id="submitSearch" value="絞り込む" >
			</div>
            <script>
                $('#datepairExample .date').datepicker({
                    'format': 'yyyy/mm/dd',
                    'autoclose': true
                });
            </script>
            <?php endif;?>
			<input type="hidden" id="id" name="id" value="<?php echo $this->product_id; ?>">
			<input type="hidden" id="tylelist" name="tylelist" value="<?php echo $this->tylelist; ?>">
			<span id="arrCondition">
			<?php 
			if (isset($this->conditions)){
				foreach ($this->conditions as $key => $condition):
				?>
				<input type="hidden" name="condition[<?php echo $key;?>]" value="<?php echo $condition; ?>">
				<input type="hidden" name="conditionkey[<?php echo $key;?>]" value="<?php echo $key; ?>">
				<?php endforeach; 
			}
		?>
			</span>
				<?php 
					if (isset($this->conditions)){
						$i=1;
						foreach ($this->conditions as $key => $condition):
							$res = explode("@@", $condition);
						?>
						<div class="condition"><b>【条件 <?php echo $i; ?>】</b>
							<table width="100%">
									 <tr class="parent">
									    <td class="name"><?php echo ($res[0]); ?></td>
									    <td class="delete" width="5px"><input class="conditiondelete" id="<?php echo $key;?>" type="button" value="x"></td>
									  </tr>
									  <tr >
									    <td colspan="2" class="child">
									    	<a href="#"><?php echo ($res[2]); ?></a></td>
									  </tr>	
							</table>
						</div>
						<?php $i++; endforeach; 
					}
				?>
		    
		    <h5><b>
		      <span class="glyphicon "></span>&nbsp;商品カテゴリー</b>
		    </h5>
		    <ul id="menu2">
		    	<?php foreach ($this->m_categorys as $key => $category):
		        ?>
		        <li> <a href="#" ><?php echo $category['parent']->getCategoryName(); 
		        ?></a>
		            <ul>
		            <?php foreach ($category['child'] as $keychild => $child):
		            ?>
		            <li>
		            	<a href="<?php echo "#".$child->getCategoryId(); ?>" class="childcate" id="<?php echo $category['parent']->getCategoryName() .'@@'. $child->getCategoryId() .'@@'. $child->getCategoryName(); ?>">
		            				<?php echo $child->getCategoryName(); ?></a></li>
		            <?php endforeach; ?>
		            </ul>
		        </li>
		        <?php endforeach; ?>
		    </ul>
	</div><!--/span-->
</form>