
<script type="text/javascript">
$(document).ready(function(){
	$( ".pagination a" ).click(function() {
	  	var id = $(this).attr('id');
	  	if (id>0){
	  		$('#frmSearch').append("<input type=\"hidden\" id=\"page\" name=\"page\" value=\"" + id + "\">");
	  		$('#frmSearch').submit();
	  	}
		return false
	});
});
</script>
<table align="center" style="margin-top:10px;">
	<tr>
		<?php if ($this->pageCount): ?>
		<td>
				<?php if ($this->pageCount > 1): ?>
			<ul class="pagination">
			<?php if (isset($this->previous)): ?>
			<li class="previous">
			<a id="<?php echo $this->previous;?>" href="<?php echo $this->url(array('page' => $this->previous)); ?>">
				<?php echo $this->escape('< '); ?>前へ</a></li>
			<?php endif; ?>

			<?php foreach ($this->pagesInRange as $page): ?>

			<?php if ($page != $this->current): ?>
			<li>
			<a id="<?php echo $page;?>" href="<?php echo $this->url(array('page' => $page)); ?>"><?php echo $page; ?></a></li>
			<?php else: ?>
			<li  class="active">
			<a id="0" href="javascript:void(0);">
			<?php echo $page; ?></a>
			<?php endif; ?>
			</li>
			<?php endforeach; ?>

			<?php if (isset($this->next)): ?>
			<li class="next">
			<a id="<?php echo $this->next;?>" href="<?php echo $this->url(array('page' => $this->next)); ?>">
				次へ<?php echo $this->escape(' >'); ?></a></li>
			<?php endif; ?>
			<?php endif; ?>
			<?php else: ?>

			<?php endif; ?>
			</ul>
		</td>
	</tr>
</table>