<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<base
	href="<?php echo $this->config["url_base"] . $this->baseUrl() . '/'; ?>" />
<meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
<meta name="description" content="" />
<meta name="keywords" content="" />
<link rel="shortcut icon" href="<?php echo $this->config['url_base'] ?>/images/favicon.ico" />
<script src="<?php echo $this->config['url_base'] ?>/js/jquery-1.11.0.js"	type="text/javascript"></script>
<script src="<?php echo $this->config['url_base'] ?>/js/jquery.form.3.5.js"	type="text/javascript"></script>
<script src="<?php echo $this->config['url_base'] ?>/js/jquery.colorbox.js"	type="text/javascript"></script>

<link href="<?php echo $this->config['url_base'] ?>/css/files.css"	rel="stylesheet" type="text/css" />
<link href="<?php echo $this->config['url_base'] ?>/css/colorbox/colorbox.css"	rel="stylesheet" type="text/css" />

<title>Select file</title>
</head>
<body >
	<?php echo $this->layout()->content; ?>
</body>
</html>
